services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: sparkuser
      POSTGRES_PASSWORD: sparkpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  spark:
    build: ./spark
    container_name: spark
    ports:
      - "4040:4040"         # Spark UI
      - "8888:8888"         # JupyterLab
    volumes:
      - ./spark/notebooks:/workspace/notebooks
    command: >
      jupyter lab
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --notebook-dir=/workspace/notebooks
        --NotebookApp.token=''
        --NotebookApp.password=''
    environment:
      PYSPARK_PYTHON: python3
    depends_on:
      - postgres

volumes:
  pg_data:
